version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.2
    ports:
      - "5044:5044"
    networks:
      - elk-network
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2
    ports:
      - "5601:5601"
    networks:
      - elk-network

networks:
  elk-network:
    driver: bridge
